---
abstract: "Add a JSON and AJAXy methods to the super-class"
author:
  - 'Lee Goddard <lgoddard@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-Mechanize-JSON
no_index:
  directory:
    - t
    - inc
requires:
  JSON::Any: 0
  Test::WWW::Mechanize: 0
version: 0.73
